on:
  issues:
    types: [opened, labeled]
#  pull_request:
#    types: [opened, labeled]
env:
  MY_GITHUB_TOKEN: ${{ secrets.NEURODESK_GITHUB_TOKEN_ISSUE_AUTOMATION }}

jobs:
  assign_issue_to_project:
    runs-on: ubuntu-latest
    name: Assign to One Project
    steps:
    - name: Assign NEW issues and NEW pull requests to New List
      uses: srggrs/assign-one-project-github-action@1.2.1
      if: github.event.action == 'opened'
      with:
        project: 'https://github.com/orgs/NeuroDesk/projects/9'
        column_name: 'New'        

    - name: Assign issues and pull requests with `bug` label to High Priority List
      uses: srggrs/assign-one-project-github-action@1.2.1
      if: |
        contains(github.event.issue.labels.*.name, 'bug') ||
        contains(github.event.pull_request.labels.*.name, 'bug')
      with:
        project: 'https://github.com/orgs/NeuroDesk/projects/9'
        column_name: 'High Priority'
